### ISSUE TITLE
Thumb cluster alternatives

### ISSUE THREAD

**Issue by fi0** [adereth/dactyl-keyboard#61]
Has anyone seen a dactyl fork with a single row 1u keys? I plan to use two to three keys per thumb.

**Comment by jgandert** [comment]
@fi0 Maybe not what you're looking for, but @ibnuda created a version with an all 1u thumb cluster, which looks great and makes sense to me, since I tend to only hit the 2u keys at the very top, so why not get two additional keys for free. 

His site is http://dactyl.siskam.link/ where you can configure your own Dactyl / Dactyl Manuform. 

Actually, I just checked and there's an option for two or three keys per thumb: 

![lightcycle](https://user-images.githubusercontent.com/3063858/85225092-fdbedb80-b3ce-11ea-9cf5-bd51eb0e4da0.png)

**Comment by fi0** [comment]
thank you @CreamyCookie
